from enum import Enum


class X509CertificateRevocationReason(str, Enum):
    AA_COMPROMISE = "AA_COMPROMISE"
    AFFILIATION_CHANGED = "AFFILIATION_CHANGED"
    CA_COMPROMISE = "CA_COMPROMISE"
    CERTIFICATE_HOLD = "CERTIFICATE_HOLD"
    CESSATION_OF_OPERATION = "CESSATION_OF_OPERATION"
    KEY_COMPROMISE = "KEY_COMPROMISE"
    PRIVILEGE_WITHDRAWN = "PRIVILEGE_WITHDRAWN"
    SUPERSEDED = "SUPERSEDED"
    UNSPECIFIED = "UNSPECIFIED"

    def __str__(self) -> str:
        return str(self.value)
